mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('pharma/', include('pharma.urls')),
    path('admin/', admin.site.urls),
]

pharma -Update/urls.py
from django.urls import path
from . import views

app_name = 'pharma'
urlpatterns = [
    path("index", views.IndexView.as_view(), name='index'),
    path('new', views.CreateView.as_view(), name='create'),
    path('cart', views.OrderView.as_view(), name='cart'),   #should implement cartview
    path('post/<int:pk>/', views.ViewPostView, name='view'),
    path('post/<int:pk>/update', views.UpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.DeleteView.as_view(), name='delete'),
    path('', views.register_request, name="register"),
    path("login", views.login_request, name="login"),

]

pharma -Update/models.py
from django.conf import settings
from django.db import models
from django.contrib.auth.models import User

class med(models.Model):
    medName = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    quantity = models.PositiveIntegerField()


    def publish(self):
        self.save()

    def __str__(self):
        return self.medName

mysite/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


# Create your forms here.

class NewUserForm(UserCreationForm):
	email = forms.EmailField(required=True)

	class Meta:
		model = User
		fields = ("username", "email", "password1", "password2")

	def save(self, commit=True):
		user = super(NewUserForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user

pharma -Update/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


# Create your forms here.

class NewUserForm(UserCreationForm):
	email = forms.EmailField(required=True)
    
	class Meta:
		model = User
		fields = ("username", "email", "password1", "password2")

	def save(self, commit=True):
		user = super(NewUserForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user

pharma/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


# Create your forms here.

class NewUserForm(UserCreationForm):
	email = forms.EmailField(required=True)
    
	class Meta:
		model = User
		fields = ("username", "email", "password1", "password2")

	def save(self, commit=True):
		user = super(NewUserForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user

pharma -Update/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.views import generic
from django.urls import reverse_lazy
from .models import med
from django.contrib.auth.models import User
from .forms import NewUserForm
from django.contrib import messages
from django.contrib.auth import login, authenticate 
from django.contrib.auth.forms import AuthenticationForm

class IndexView(generic.ListView):
    template_name = 'pharma/index.html'
    context_object_name = 'med_list'

    def get_queryset(self):
        return med.objects.all()
    
    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['count'] =  med.objects.all().count()
        return context

class CreateView(generic.edit.CreateView):
    template_name = 'pharma/create.html'
    model = med
    fields = ['medName','price', 'quantity']
    success_url = reverse_lazy('pharma:index')


class OrderView(generic.ListView):
    template_name = 'pharma/cart.html'
    context_object_name = 'med_list'

    def get_queryset(self):
        return med.objects.order_by('-medName')
    

def ViewPostView(request, pk):
    Medi = get_object_or_404(med, pk=pk)
    current_user = request.user
    print (current_user.id)
    return render(request, 'pharma/view.html', {'med': Medi})


class UpdateView(generic.edit.UpdateView):
    template_name = 'pharma/update.html'
    model = med
    fields = ['medName','price', 'quantity']
    success_url = reverse_lazy('pharma:index')

class DeleteView(generic.edit.DeleteView):
    template_name = 'pharma/delete.html'
    model = med
    success_url = reverse_lazy('pharma:index')


def register_request(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)   
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "Registration successful." )
            return redirect("pharma:index")
        messages.error(request, "Unsuccessful registration. Invalid information.")
    form = NewUserForm()
    return render (request=request, template_name="pharma/register.html", context={"register_form":form})

def login_request(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"You are now logged in as {username}.")
                return redirect("pharma:index")
            else:
                messages.error(request,"Invalid username or password.")
        else:
            messages.error(request,"Invalid username or password.")
    form = AuthenticationForm()
    return render(request=request, template_name="pharma/login.html", context={"login_form":form})

greetings/templates/greetings/update.html
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
    <a href="{% url 'greetings:delete' greeting.id %}">delete</a>
</form>

pharma -Update/templates/pharma/Order.html
<!-- {% extends 'pharma/start.html' %}
{% block create %}{% endblock %}
{% block content %}
{% load static %} -->
<!-- <link rel="stylesheet" type="text/css" href="{% static 'prescriptions/styles.css' %}"> -->
<!-- <a href="{% url 'pharma:index' %}">
    <input type="button" value="Home">
</a> -->
<!-- {% if med_list %}
    {% for med in med_list %}
        <article class="post">
            <h2><a href="{% url 'pharma:view' pk=med.pk %}">{{ med.medName }}</a></h2>
            <p>Price: ${{ med.price|linebreaksbr }}</p>
            <p>Quantity: {{ med.quantity|linebreaksbr }}</p>
        </article>
    {% endfor %}
{% else %}
    <p>No Medicines are available.</p>
{% endif %}
{% endblock %} -->

pharma -Update/templates/pharma/cart.html
{% block content %}
{% load static %}
<head>
    <title>Pharmacy</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
</head>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'pharma:index' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'pharma:create' %}">Add Medicine</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'pharma:cart' %}">Shopping Cart <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'pharma:login' %}">Log Out</a>
        </li>
      </ul>
    </div>
  </nav>
<h1>Please start adding needed Medicine</h1>
<h2>List of Medicines</h2>
<!-- <link rel="stylesheet" type="text/css" href="{% static 'prescriptions/styles.css' %}"> -->
{% if med_list %}
    {% for med in med_list %}
        <article class="post">
            <p>Medicine Name: <a href="{% url 'pharma:view' pk=med.pk %}">{{ med.medName }}</a></p>
            <p>Price: ${{ med.price|linebreaksbr }}</p>
            <p>Quantity: {{ med.quantity|linebreaksbr }}</p>
        </article>
    {% endfor %}
{% else %}
    <p>No Medicines are available.</p>
{% endif %}
<hr>
<h1>Your Shopping Cart</h1>
<h2>List of added Medicines</h2>

{% endblock %}

pharma -Update/templates/pharma/cartContent.html
{% block content %}
<h1>Please start adding needed Medicine</h1>
<h2>List of Medicines</h2>
{% load static %}
<!-- <link rel="stylesheet" type="text/css" href="{% static 'prescriptions/styles.css' %}"> -->
{% if med_list %}
    {% for med in med_list %}
        <article class="post">
            <p>Medicine Name: <a href="{% url 'pharma:view' pk=med.pk %}">{{ med.medName }}</a></p>
            <p>Price: ${{ med.price|linebreaksbr }}</p>
            <p>Quantity: {{ med.quantity|linebreaksbr }}</p>
        </article>
    {% endfor %}
{% else %}
    <p>No Medicines are available.</p>
{% endif %}
<a href="{% url 'pharma:index' %}">
    <input type="button" value="Home">
</a>
<hr>
<h1>Your Shopping Cart</h1>
<h2>List of added Medicines</h2>
{% endblock %}

pharma -Update/templates/pharma/create.html
{% load static %}
<head>
    <title>Pharmacy</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
</head>
<!-- <link rel="stylesheet" type="text/css" href="{% static 'prescriptions/styles.css' %}"> -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'pharma:index' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'pharma:create' %}">Add Medicine <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'pharma:cart' %}">Shopping Cart</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'pharma:login' %}">Log Out</a>
        </li>
      </ul>
    </div>
  </nav>
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>

pharma -Update/templates/pharma/delete.html
{% load static %}
<head>
    <title>Pharmacy</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
</head>
<!-- <link rel="stylesheet" type="text/css" href="{% static 'prescriptions/styles.css' %}"> -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'pharma:index' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'pharma:create' %}">Add Medicine</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'pharma:cart' %}">Shopping Cart</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'pharma:login' %}">Log Out</a>
        </li>
      </ul>
    </div>
  </nav>
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete the following medicine "{{ object.medName }}"?</p>
    <input type="submit" value="Confirm">
</form>

pharma -Update/templates/pharma/index.html
{% extends 'pharma/start.html' %}
{% block content %}
{% load static %}
<head>
    <title>Pharmacy</title>
        Welcome {{user.username}}!
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
</head>
<!-- <link rel="stylesheet" type="text/css" href="{% static 'prescriptions/styles.css' %}"> -->
{% if med_list %}
    <p>Medicine count: {{count}}</p>
    {% for med in med_list %}
        <article class="post">
            <p>Medicine Name: <a href="{% url 'pharma:view' pk=med.pk %}">{{ med.medName }}</a></p>
            <p>Price: ${{ med.price|linebreaksbr }}</p>
            <p>Quantity: {{ med.quantity|linebreaksbr }}</p>
        </article>
    {% endfor %}
{% else %}
    <p>No Medicines are available.</p>
{% endif %}
{% endblock %}

pharma -Update/templates/pharma/login.html
{% block content %}      
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
{% load crispy_forms_tags %}

<!--Login--> 
<div class="container py-5">
  <h1>Login</h1>
  <form method="POST">
    {% csrf_token %}
    {{ login_form|crispy }}
    <button class="btn btn-primary" type="submit">Login</button>
  </form>
  <p class="text-center">Don't have an account? <a href="{% url 'pharma:register'%}">Create an account</a>.</p>
</div>

{{form.username}}
{{form.password}}

{% endblock %}

pharma -Update/templates/pharma/register.html
{% block content %} 
{% load static %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
{% load crispy_forms_tags %}  
<link rel="stylesheet" href="box_style.css">       

<!--Register--> 
<div class="container py-5">
	<header class = "titlebackground">
		<h1>Register</h1>
	</header>
	
	<form method="POST">
		{% csrf_token %}
		{{ register_form|crispy }}                    
		<button class="btn btn-primary" type="submit">Register</button>
	</form>
	<p class="text-center">If you already have an account, <a href="{% url 'pharma:login'%}">login</a> instead.</p>
</div>
{{ form.username}}
{{form.email}}
{{form.password1}}
{{form.password2}}

{% endblock %}

pharma -Update/templates/pharma/start.html
{% load static %}
<!-- <link rel="stylesheet" type="text/css" href="{% static 'prescriptions/styles.css' %}"> -->
<!DOCTYPE html>
<html>
    <head>
        <title>Pharmacy</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">Navbar</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
              <ul class="navbar-nav">
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'pharma:index' %}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'pharma:create' %}">Add Medicine</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'pharma:cart' %}">Shopping Cart</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'pharma:login' %}">Log Out</a>
                </li>
              </ul>
            </div>
          </nav>
        <main class="container">
            <div class="row">
                <div class="col">
                    {% block content %}
                        {% if med_list %}
                            {% for med in med_list %}
                                <article class="post">
                                    <p><a href="{% url 'pharma:view' pk=med.pk %}">{{ med.medName }}</a></p>
                                    <p>Price: ${{ med.price|linebreaksbr }}</p>
                                    <p>Quantity: {{ med.quantity|linebreaksbr }}</p>
                                </article>
                            {% endfor %}
                        {% else %}
                            <p>No Medicines are available.</p>
                        {% endif %}
                    {% endblock %}
                </div>
            </div>
        </main>
    </body>
</html>

pharma -Update/templates/pharma/update.html
{% load static %}
<head>
    <title>Pharmacy</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
</head>
<!-- <link rel="stylesheet" type="text/css" href="{% static 'prescriptions/styles.css' %}"> -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'pharma:index' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'pharma:create' %}">Add Medicine</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'pharma:cart' %}">Shopping Cart</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'pharma:login' %}">Log Out</a>
        </li>
      </ul>
    </div>
  </nav>
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
    <a href="{% url 'pharma:delete' med.id %}">
        <input type="button" value="Delete">
    </a>
</form>

pharma -Update/templates/pharma/view.html
{% extends 'pharma/start.html' %}
{% block create %}{% endblock %}
{% block content %}
{% load static %}
<head>
    <title>Pharmacy</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
</head>
<!-- <link rel="stylesheet" type="text/css" href="{% static 'prescriptions/styles.css' %}"> -->
    <article class="post">
        <h2>{{ med.medName }}</h2>
        <a href="{% url 'pharma:update' pk=med.pk %}">
            <input type="button" value="Update/Edit the Post">
        </a>
        <p>Price: ${{ med.price|linebreaksbr }}</p>
        <p>Quantity: {{ med.quantity|linebreaksbr }}</p>
    </article>
{% endblock %}

pharma/templates/pharma/cart.html
{% block content %}
<h1>Please start adding needed Medicine</h1>
<h2>List of Medicines</h2>
{% load static %}
<!-- <link rel="stylesheet" type="text/css" href="{% static 'prescriptions/styles.css' %}"> -->
{% if med_list %}
    {% for med in med_list %}
        <article class="post">
            <p>Medicine Name: <a href="{% url 'pharma:view' pk=med.pk %}">{{ med.medName }}</a></p>
            <p>Price: ${{ med.price|linebreaksbr }}</p>
            <p>Quantity: {{ med.quantity|linebreaksbr }}</p>
        </article>
    {% endfor %}
{% else %}
    <p>No Medicines are available.</p>
{% endif %}
<a href="{% url 'pharma:index' %}">
    <input type="button" value="Home">
</a>
<hr>
<h1>Your Shopping Cart</h1>
<h2>List of added Medicines</h2>
{% endblock %}

pharma/templates/pharma/login.html
{% block content %}      
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
{% load crispy_forms_tags %}

<!--Login--> 
<div class="container py-5">
  <h1>Login</h1>
  <form method="POST">
    {% csrf_token %}
    {{ login_form|crispy }}
    <button class="btn btn-primary" type="submit">Login</button>
  </form>
  <p class="text-center">Don't have an account? <a href="{% url 'pharma:register'%}">Create an account</a>.</p>
</div>

{{form.username}}
{{form.password}}

{% endblock %}

pharma/templates/pharma/order.html
<!-- {% extends 'pharma/start.html' %}
{% block create %}{% endblock %}
{% block content %}
{% load static %} -->
<!-- <link rel="stylesheet" type="text/css" href="{% static 'prescriptions/styles.css' %}"> -->
<!-- <a href="{% url 'pharma:index' %}">
    <input type="button" value="Home">
</a> -->
<!-- {% if med_list %}
    {% for med in med_list %}
        <article class="post">
            <h2><a href="{% url 'pharma:view' pk=med.pk %}">{{ med.medName }}</a></h2>
            <p>Price: ${{ med.price|linebreaksbr }}</p>
            <p>Quantity: {{ med.quantity|linebreaksbr }}</p>
        </article>
    {% endfor %}
{% else %}
    <p>No Medicines are available.</p>
{% endif %}
{% endblock %} -->

pharma/templates/pharma/register.html
{% block content %} 
{% load static %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
{% load crispy_forms_tags %}         

<!--Register--> 
<div class="container py-5">
	<h1>Register</h1>
	<form method="POST">
		{% csrf_token %}
		{{ register_form|crispy }}                    
		<button class="btn btn-primary" type="submit">Register</button>
	</form>
	<p class="text-center">If you already have an account, <a href="{% url 'pharma:login'%}">login</a> instead.</p>
</div>
{{ form.username}}
{{form.email}}
{{form.password1}}
{{form.password2}}

{% endblock %}